### ISSUE TITLE
Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by kacperpaczos** [react-gjs/gest#161]
After installation, I run the yarn gest and I get an error. What am I doing wrong?
```
yarn gest
yarn run v1.22.19
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
info If you think this is a bug, please open a bug report with the information provided in "/home/XXX/Dokumenty/JSX/gest/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ncpa0cpl** [comment]
yarn's being stupid, in the `.npmrc` file there's this line:
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
NPM_TOKEN is a env variable, this is only needed for publishing the package to the npm registry, you can either remove this line or create this env variable locally, it doesn't have to contain anything, just `export NPM_TOKEN=` would do the job
